<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>GrpCurl.Net.Tests.Unit</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.MTP">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Src\GrpCurl.Net\GrpCurl.Net.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\TestProtosets\**\*.protoset" CopyToOutputDirectory="PreserveNewest" LinkBase="TestProtosets" />
        <Content Include="..\TestCertificates\**\*" CopyToOutputDirectory="PreserveNewest" LinkBase="TestCertificates" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shouldly" />
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
