<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>Gql2Grpc.Tests</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="TestData\**\*" CopyToOutputDirectory="PreserveNewest" LinkBase="TestData" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.MTP">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Grpc.AspNetCore" />
        <PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Src\Gql2Grpc\Gql2Grpc.csproj" />
        <ProjectReference Include="..\..\Src\GrpCurl.Net\GrpCurl.Net.csproj" />
        <ProjectReference Include="..\GrpCurl.Net.TestServer\GrpCurl.Net.TestServer.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shouldly" />
        <Using Include="Xunit" />
    </ItemGroup>

</Project>
